<LoginScreen>:
    GridLayout:
        cols:1
        GridLayout:
            cols:1
            Label:
                text: "User Login"
            TextInput:
                id: username
                hint_text:"Username"
            TextInput:
                id: password
                hint_text:"Password"
            Label:
                id: login_wrong
                text: ""
            Button:
                text:"Login"
                on_press: root.login(root.ids.username.text, root.ids.password.text)
        GridLayout:
            cols:2
            Button:
                text:"Forgot Password?"
            Button:
                text:"Sign up"
                on_press:root.sign_up()

<SignUpScreen>:
    GridLayout:
        cols:1
        Label:
            text:"Door to Another Dimension, Bitch!"
        TextInput:
            id: username
            hint_text:"New Username"
        TextInput:
            id: password
            hint_text:"New Password"
        GridLayout:
            cols:2
            Button:
                text:"Cancel"
                on_press: root.goto_login()
            Button:
                text:"Submit"
                on_press: root.add_user(root.ids.username.text, root.ids.password.text)
                
<SignUpScreenSuccess>:
    GridLayout:
        cols:1
        Label:
            text:"Welcome asshole to Another Dimension!"
        Button:
            text:"Login page"
            on_press: root.goto_login()
            
<LoginScreenSuccess>:
    GridLayout:
        cols:1
        Button:
            text:"Logout"
            on_press: root.log_out()
        Label:
            text:"How you doin.?"
        TextInput:
            hint_text:"Try: happy, sad boi, fucked up.."
        Button:
            text:"Remove Toxins"
            
        Label:
            text: ""

<RootWidget>:
    LoginScreen:
        name:"login_screen"

    SignUpScreen:
        name:"signup_screen"

    SignUpScreenSuccess:
        name:"signup_screen_success"

    LoginScreenSuccess:
        name: "login_screen_success"